### ISSUE TITLE
node 报错

### ISSUE THREAD

**Issue by weiqiangcai** [wisinfun/Alfred-Workflow-yuque#5]
```
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (file:///Users/miotlink/Library/Application%20Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.10BC0773-BBC3-4B63-A4B8-F9116E04BA63/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Request._onResponseBase (file:///Users/miotlink/Library/Application%20Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.10BC0773-BBC3-4B63-A4B8-F9116E04BA63/node_modules/got/dist/source/core/index.js:704:22)
    at async Request._onResponse (file:///Users/miotlink/Library/Application%20Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.10BC0773-BBC3-4B63-A4B8-F9116E04BA63/node_modules/got/dist/source/core/index.js:743:13)
```

-
语雀 1.6
Alfred 5.5
darwin 23.4.0

**Comment by xiaxiansong** [comment]
我也是
